services:
  php:
    image: php:8.2-fpm
    build: .
    container_name: php
    volumes:
      - ./../app:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ceramique
      MYSQL_USER: ceramique
      MYSQL_PASSWORD: ceramique
    ports:
      - 3306:3306 # Le port local est toujours 3306
    volumes:
      - ./db_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:v1.23.0
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MAILPIT_RELAY=127.0.0.1:25

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./../app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
 
  adminer:
    image: adminer:4.17.1
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8081:8080
    depends_on:
      - db

 # phpmyadmin:
 #   image: phpmyadmin/phpmyadmin:latest
 #   container_name: phpmyadmin
 #   environment:
 #     PMA_HOST: mariadb # Nom du conteneur MariaDB
 #     PMA_PORT: 3306    # Port interne utilisé par phpMyAdmin
 #     MYSQL_ROOT_PASSWORD: root
 #   ports:
 #     - "8081:80" # Accès à phpMyAdmin via le port 8081
 #   depends_on:
 #     - mariadb
 
#networks:
#test_networks:
volumes:
  db_data:
